### ISSUE TITLE
[PE-D][Tester B] Unclear error message for `list`

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-2/tp#233] opened 2024-11-08 16:55 UTC
If I don't follow the command format for `list`, the error message is as follow:
![image.png](https://raw.githubusercontent.com/reginateh/ped/main/files/f5bd5a1b-0a87-4292-82d8-9b7632df6736.png)
It would be better to display the command format for `list`.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: reginateh/ped#3

**Comment by Andrew22Teoh** [comment] 2024-11-10 02:23
Duplicate of other

**Closed as completed by Andrew22Teoh** 2024-11-10 02:23 UTC
Labels: good-bug, feature-flaw-bug
