### ISSUE TITLE
[PE-D][Tester E] Find n/ or p/ followed by nothing returns all the contacts with that field.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-2/tp#294] opened 2024-11-08 23:59 UTC
![Screenshot 2024-11-08 at 8.22.48 PM.png](https://raw.githubusercontent.com/yu-sutong/ped/main/files/7fc525a5-62e1-4443-a273-bc725433e9b9.png)
Not reflected in the UG.
![Screenshot 2024-11-08 at 8.24.10 PM.png](https://raw.githubusercontent.com/yu-sutong/ped/main/files/b96add67-6ba4-4136-900c-360748434223.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: yu-sutong/ped#16

**Comment by AbdulrahmanAlRammah** [comment] 2024-11-12 02:34
Duplicate of #248

**Closed as completed by AbdulrahmanAlRammah** 2024-11-12 02:34 UTC
Labels: good-bug, documentation-bug
